# Generated by Django 4.1.5 on 2023-03-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50)),
                ('brithdate', models.DateField(blank=True)),
                ('gender', models.BooleanField(choices=[('male', 'male'), ('famale', 'famale')])),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.DateField()),
                ('imdb', models.URLField(blank=True)),
                ('genre', models.CharField(max_length=50)),
                ('actors', models.ManyToManyField(to='Cenima.actor')),
            ],
        ),
    ]
