# Generated by Django 4.1.5 on 2023-03-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cenima', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('thiller', 'thiller'), ('horror', 'horror'), ('sports', 'sports'), ('melody', 'melody'), ('comedy', 'comedy')], max_length=400),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
    ]
